// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StbDigitalHub.Api.Data;

#nullable disable

namespace StbDigitalHub.Api.Migrations
{
    [DbContext(typeof(StbDigitalHubDbContext))]
    [Migration("20260917112703_AddDigiTransfert")]
    partial class AddDigiTransfert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Beneficiaire", b =>
                {
                    b.Property<long>("IdBeneficiaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdBeneficiaire"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Alias")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Banque")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Favori")
                        .HasColumnType("bit");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rib")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("IdBeneficiaire");

                    b.HasIndex("IdClient", "Rib");

                    b.ToTable("Beneficiaires");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CarteBancaire", b =>
                {
                    b.Property<long>("IdCarte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCarte"));

                    b.Property<bool>("AlertesMarteActives")
                        .HasColumnType("bit");

                    b.Property<decimal>("AllocationAnnuelle")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AllocationConsommeeAnnee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AnneeAllocation")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateDebutEcommerceIntl")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFinEcommerceIntl")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFinPlafondTemporaire")
                        .HasColumnType("date");

                    b.Property<string>("DevisePreferee")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("EcommerceInternationalActif")
                        .HasColumnType("bit");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroComplet")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("NumeroMasque")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<bool>("PaiementsEnLigneActifs")
                        .HasColumnType("bit");

                    b.Property<decimal>("PlafondPaiement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlafondRecharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlafondRetrait")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PlafondTemporaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Solde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoldeMaximal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("TokenCarte")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IdCarte");

                    b.HasIndex("IdClient", "TokenCarte")
                        .IsUnique();

                    b.ToTable("CartesBancaires");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Client", b =>
                {
                    b.Property<long>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdClient"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDerniereConnexionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailConfirme")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoProfilUrl")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdClient");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CompteBancaire", b =>
                {
                    b.Property<long>("IdCompte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCompte"));

                    b.Property<DateTime>("DateOuvertureUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NumeroCompte")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Rib")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<decimal>("Solde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IdCompte");

                    b.HasIndex("IdClient", "NumeroCompte")
                        .IsUnique();

                    b.ToTable("ComptesBancaires");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CompteEpargne", b =>
                {
                    b.Property<long>("IdCompteEpargne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCompteEpargne"));

                    b.Property<DateTime>("DateCalculInteretsUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCompte")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ObjectifEpargne")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TauxInteret")
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("IdCompteEpargne");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCompte")
                        .IsUnique();

                    b.ToTable("ComptesEpargne");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Credit", b =>
                {
                    b.Property<long>("IdCredit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCredit"));

                    b.Property<DateTime>("DateDebutUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinPrevueUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DureeMois")
                        .HasColumnType("int");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdDemande")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Mensualite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantAccorde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("SoldeRestantDu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<decimal>("TauxInteret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeCredit")
                        .HasColumnType("int");

                    b.HasKey("IdCredit");

                    b.HasIndex("IdDemande")
                        .IsUnique()
                        .HasFilter("[IdDemande] IS NOT NULL");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("IdClient", "DateDebutUtc");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.DemandeCredit", b =>
                {
                    b.Property<long>("IdDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdDemande"));

                    b.Property<decimal>("CoutTotalEstime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateDecisionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDemandeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DureeMois")
                        .HasColumnType("int");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdSimulation")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MensualiteEstimee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantDemande")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotifDecision")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RevenuMensuel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeCredit")
                        .HasColumnType("int");

                    b.HasKey("IdDemande");

                    b.HasIndex("IdSimulation");

                    b.HasIndex("IdClient", "DateDemandeUtc");

                    b.ToTable("DemandesCredit");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.DemandeRetrait", b =>
                {
                    b.Property<long>("IdDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdDemande"));

                    b.Property<DateTime?>("DateDecisionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDemandeUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdCompteEpargne")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotifDecision")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("IdDemande");

                    b.HasIndex("IdCompteEpargne", "DateDemandeUtc");

                    b.ToTable("DemandesRetrait");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Echeance", b =>
                {
                    b.Property<long>("IdEcheance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEcheance"));

                    b.Property<decimal>("Capital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DateEcheance")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DatePaiementUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdCredit")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Interet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("Payee")
                        .HasColumnType("bit");

                    b.Property<decimal>("SoldeRestantDu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEcheance");

                    b.HasIndex("IdCredit", "Numero")
                        .IsUnique();

                    b.ToTable("Echeances");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.MouvementEpargne", b =>
                {
                    b.Property<long>("IdMouvement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMouvement"));

                    b.Property<DateTime>("DateMouvementUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdCompteEpargne")
                        .HasColumnType("bigint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IdMouvement");

                    b.HasIndex("IdCompteEpargne", "DateMouvementUtc");

                    b.ToTable("MouvementsEpargne");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Notification", b =>
                {
                    b.Property<long>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdNotification"));

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdCarte")
                        .HasColumnType("bigint");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdTransaction")
                        .HasColumnType("bigint");

                    b.Property<bool>("Lue")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdClient", "DateCreationUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxTentatives")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Tentatives")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdClient", "CreatedAtUtc");

                    b.ToTable("OtpChallenges");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.PendingCardAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateConfirmationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpirationUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdCarte")
                        .HasColumnType("bigint");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdTransaction")
                        .HasColumnType("bigint");

                    b.Property<string>("MessageResultat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Recapitulatif")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeAction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("IdCarte");

                    b.HasIndex("IdClient", "DateCreationUtc");

                    b.ToTable("PendingCardActions");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.PendingCreditAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateConfirmationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpirationUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdDemande")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdSimulation")
                        .HasColumnType("bigint");

                    b.Property<string>("MessageResultat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Recapitulatif")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeAction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("IdClient", "DateCreationUtc");

                    b.ToTable("PendingCreditActions");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.PendingEpargneAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateConfirmationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpirationUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdCompteEpargne")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdDemandeRetrait")
                        .HasColumnType("bigint");

                    b.Property<string>("MessageResultat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Recapitulatif")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeAction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("IdClient", "DateCreationUtc");

                    b.ToTable("PendingEpargneActions");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.RecuVirement", b =>
                {
                    b.Property<long>("IdRecu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecu"));

                    b.Property<DateTime>("DateGenerationUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdVirement")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceVirement")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdRecu");

                    b.HasIndex("IdVirement")
                        .IsUnique();

                    b.ToTable("RecusVirement");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.RegleEpargneIntelligente", b =>
                {
                    b.Property<long>("IdRegle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRegle"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DerniereExecutionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Frequence")
                        .HasColumnType("int");

                    b.Property<long>("IdCompteEpargne")
                        .HasColumnType("bigint");

                    b.Property<int>("TypeRegle")
                        .HasColumnType("int");

                    b.Property<decimal>("Valeur")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdRegle");

                    b.HasIndex("IdCompteEpargne");

                    b.ToTable("ReglesEpargne");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.SimulationCredit", b =>
                {
                    b.Property<long>("IdSimulation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSimulation"));

                    b.Property<decimal>("CoutTotalEstime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateSimulationUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DureeMois")
                        .HasColumnType("int");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MensualiteEstimee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NiveauEligibilite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("RevenuMensuel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TauxAnnuel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TauxEndettement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeCredit")
                        .HasColumnType("int");

                    b.HasKey("IdSimulation");

                    b.HasIndex("IdClient", "DateSimulationUtc");

                    b.ToTable("SimulationsCredit");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.TransactionCarte", b =>
                {
                    b.Property<long>("IdTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTransaction"));

                    b.Property<string>("Commercant")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("DateTransactionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Devise")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long>("IdCarte")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantDevise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Pays")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeOperation")
                        .HasColumnType("int");

                    b.HasKey("IdTransaction");

                    b.HasIndex("IdCarte");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("TransactionsCarte");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.TransactionCompte", b =>
                {
                    b.Property<long>("IdTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTransaction"));

                    b.Property<DateTime>("DateTransactionUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdCompte")
                        .HasColumnType("bigint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeMouvement")
                        .HasColumnType("int");

                    b.HasKey("IdTransaction");

                    b.HasIndex("IdCompte");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("TransactionsCompte");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Virement", b =>
                {
                    b.Property<long>("IdVirement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdVirement"));

                    b.Property<DateTime?>("DateConfirmationOtpUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExecutionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOperationUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DelaiEstime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Frais")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("IdBeneficiaire")
                        .HasColumnType("bigint");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCompteSource")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IdOtpChallenge")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IntraStb")
                        .HasColumnType("bit");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("IdVirement");

                    b.HasIndex("IdBeneficiaire");

                    b.HasIndex("IdCompteSource");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("IdClient", "DateOperationUtc");

                    b.ToTable("Virements");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Beneficiaire", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("Beneficiaires")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CarteBancaire", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("Cartes")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CompteBancaire", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("Comptes")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CompteEpargne", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("ComptesEpargne")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StbDigitalHub.Api.Entities.CompteBancaire", "Compte")
                        .WithMany()
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Credit", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("Credits")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StbDigitalHub.Api.Entities.DemandeCredit", "Demande")
                        .WithOne("Credit")
                        .HasForeignKey("StbDigitalHub.Api.Entities.Credit", "IdDemande")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Client");

                    b.Navigation("Demande");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.DemandeCredit", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("DemandesCredit")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StbDigitalHub.Api.Entities.SimulationCredit", "Simulation")
                        .WithMany()
                        .HasForeignKey("IdSimulation")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Client");

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.DemandeRetrait", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.CompteEpargne", "CompteEpargne")
                        .WithMany("DemandesRetrait")
                        .HasForeignKey("IdCompteEpargne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteEpargne");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Echeance", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Credit", "Credit")
                        .WithMany("Echeances")
                        .HasForeignKey("IdCredit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credit");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.MouvementEpargne", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.CompteEpargne", "CompteEpargne")
                        .WithMany("Mouvements")
                        .HasForeignKey("IdCompteEpargne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteEpargne");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Notification", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("Notifications")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.OtpChallenge", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("OtpChallenges")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.PendingCardAction", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.CarteBancaire", "Carte")
                        .WithMany()
                        .HasForeignKey("IdCarte")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carte");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.PendingCreditAction", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.PendingEpargneAction", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.RecuVirement", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Virement", "Virement")
                        .WithOne("Recu")
                        .HasForeignKey("StbDigitalHub.Api.Entities.RecuVirement", "IdVirement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Virement");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.RegleEpargneIntelligente", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.CompteEpargne", "CompteEpargne")
                        .WithMany("Regles")
                        .HasForeignKey("IdCompteEpargne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteEpargne");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.SimulationCredit", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("SimulationsCredit")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.TransactionCarte", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.CarteBancaire", "Carte")
                        .WithMany("Transactions")
                        .HasForeignKey("IdCarte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carte");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.TransactionCompte", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.CompteBancaire", "Compte")
                        .WithMany("Transactions")
                        .HasForeignKey("IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Virement", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Beneficiaire", "Beneficiaire")
                        .WithMany("Virements")
                        .HasForeignKey("IdBeneficiaire")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("Virements")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StbDigitalHub.Api.Entities.CompteBancaire", "CompteSource")
                        .WithMany()
                        .HasForeignKey("IdCompteSource")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Beneficiaire");

                    b.Navigation("Client");

                    b.Navigation("CompteSource");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Beneficiaire", b =>
                {
                    b.Navigation("Virements");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CarteBancaire", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Client", b =>
                {
                    b.Navigation("Beneficiaires");

                    b.Navigation("Cartes");

                    b.Navigation("Comptes");

                    b.Navigation("ComptesEpargne");

                    b.Navigation("Credits");

                    b.Navigation("DemandesCredit");

                    b.Navigation("Notifications");

                    b.Navigation("OtpChallenges");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("SimulationsCredit");

                    b.Navigation("Virements");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CompteBancaire", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CompteEpargne", b =>
                {
                    b.Navigation("DemandesRetrait");

                    b.Navigation("Mouvements");

                    b.Navigation("Regles");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Credit", b =>
                {
                    b.Navigation("Echeances");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.DemandeCredit", b =>
                {
                    b.Navigation("Credit");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Virement", b =>
                {
                    b.Navigation("Recu");
                });
#pragma warning restore 612, 618
        }
    }
}
