// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StbDigitalHub.Api.Data;

#nullable disable

namespace StbDigitalHub.Api.Migrations
{
    [DbContext(typeof(StbDigitalHubDbContext))]
    [Migration("20260805201106_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CarteBancaire", b =>
                {
                    b.Property<long>("IdCarte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCarte"));

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFinPlafondTemporaire")
                        .HasColumnType("date");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroComplet")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("NumeroMasque")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<bool>("PaiementsEnLigneActifs")
                        .HasColumnType("bit");

                    b.Property<decimal>("PlafondPaiement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlafondRetrait")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PlafondTemporaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Solde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("TokenCarte")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IdCarte");

                    b.HasIndex("IdClient", "TokenCarte")
                        .IsUnique();

                    b.ToTable("CartesBancaires");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Client", b =>
                {
                    b.Property<long>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdClient"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDerniereConnexionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailConfirme")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoProfilUrl")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdClient");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Notification", b =>
                {
                    b.Property<long>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdNotification"));

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdCarte")
                        .HasColumnType("bigint");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdTransaction")
                        .HasColumnType("bigint");

                    b.Property<bool>("Lue")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdClient", "DateCreationUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxTentatives")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Tentatives")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdClient", "CreatedAtUtc");

                    b.ToTable("OtpChallenges");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdClient")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.TransactionCarte", b =>
                {
                    b.Property<long>("IdTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTransaction"));

                    b.Property<string>("Commercant")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("DateTransactionUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdCarte")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeOperation")
                        .HasColumnType("int");

                    b.HasKey("IdTransaction");

                    b.HasIndex("IdCarte");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("TransactionsCarte");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CarteBancaire", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("Cartes")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Notification", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("Notifications")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.OtpChallenge", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("OtpChallenges")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.Client", "Client")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.TransactionCarte", b =>
                {
                    b.HasOne("StbDigitalHub.Api.Entities.CarteBancaire", "Carte")
                        .WithMany("Transactions")
                        .HasForeignKey("IdCarte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carte");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.CarteBancaire", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StbDigitalHub.Api.Entities.Client", b =>
                {
                    b.Navigation("Cartes");

                    b.Navigation("Notifications");

                    b.Navigation("OtpChallenges");

                    b.Navigation("PasswordResetTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
